//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AirPort.Module.BusinessObjects.Galaxy_db
{

    public partial class com_Pilot_Aircraft : XPLiteObject
    {
        int _Id;
        [Key(true)]
        [Browsable(false)]
        public int Id
        {
            get { return _Id; }
            set { SetPropertyValue<int>("Id", ref _Id, value); }
        }
        rb_Pilot _Id_Pilot;
        [Indexed(@"Id_Aircraft", Name = @"rb_Aircraft_rb_Pilot_Unique", Unique = true)]
        [Association(@"com_Pilot_AircraftReferencesrb_Pilot")]
        public rb_Pilot Id_Pilot
        {
            get { return _Id_Pilot; }
            set { SetPropertyValue<rb_Pilot>("Id_Pilot", ref _Id_Pilot, value); }
        }
        rb_Aircraft _Id_Aircraft;
        [Association(@"com_Pilot_AircraftReferencesrb_Aircraft")]
        public rb_Aircraft Id_Aircraft
        {
            get { return _Id_Aircraft; }
            set { SetPropertyValue<rb_Aircraft>("Id_Aircraft", ref _Id_Aircraft, value); }
        }
    }

}
