//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AirPort.Module.BusinessObjects.Galaxy_db
{

    public partial class rb_Airport : XPLiteObject
    {
        int _Id;
        [Key(true)]
        [Browsable(false)]
        public int Id
        {
            get { return _Id; }
            set { SetPropertyValue<int>("Id", ref _Id, value); }
        }
        string _Name;
        [DevExpress.Persistent.Validation.RuleRequiredField]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        [Association(@"com_Airport_Pilot_AircraftReferencesrb_Airport")]
        public XPCollection<com_Airport_Aircraft> com_Airport_Pilot_Aircrafts { get { return GetCollection<com_Airport_Aircraft>("com_Airport_Pilot_Aircrafts"); } }
        [Association(@"rb_PilotReferencesrb_Airport")]
        public XPCollection<rb_Pilot> rb_Pilots { get { return GetCollection<rb_Pilot>("rb_Pilots"); } }
    }

}
